hidden_size: 20
dropout: 0.2
seed: 42
ft_epochs: 150
pt_epochs: 50
early_stopping: 20
pretrain_learning_rate: 0.005
finetune_learning_rate: 0.001
weight_decay: 0.001 
# L2 regularization parameter for Adam optimizer
trn_offset: 1.0
tst_val_offset: 1.0
out_dir: output

# SMAP modality (multimodality pipeline)
use_smap: false
d_smap: 32
